services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/projetodb
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile    # Dockerfile está aqui
    container_name: next-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend


  db:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projetodb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  frontend-data: